services:
  _defaults:
    public: true

  # Demo configuration text form
  prestashop.module.swiperslider.form.type.swiper_configuration_text:
    class: 'PrestaShop\Module\SwiperSlider\Form\SwiperConfigurationFormType'
    parent: 'form.type.translatable.aware'
    public: true
    tags:
      - { name: form.type }

  prestashop.module.swiperslider.form.swiper_configuration_text_data_configuration:
    class: 'PrestaShop\Module\SwiperSlider\Form\SwiperConfigurationTextDataConfiguration'
    arguments: [ '@prestashop.adapter.legacy.configuration' ]


  prestashop.module.swiperslider.form.swiper_configuration_text_form_data_provider:
    class: 'PrestaShop\Module\SwiperSlider\Form\SwiperConfigurationTextFormDataProvider'
    arguments:
      - '@prestashop.module.swiperslider.form.swiper_configuration_text_data_configuration'

  prestashop.module.swiperslider.form.swiper_configuration_text_form_data_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\Handler'
    arguments:
      - '@form.factory'
      - '@prestashop.core.hook.dispatcher'
      - '@prestashop.module.swiperslider.form.swiper_configuration_text_form_data_provider'
      - 'PrestaShop\Module\SwiperSlider\Form\SwiperConfigurationFormType'
      - 'SwiperConfiguration'

